//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: global::System.Reflection.AssemblyVersion("0.2.0.15")]
[assembly: global::System.Reflection.AssemblyFileVersion("0.2.0.15")]

// Generated by the MSBuild WriteCodeFragment class on 2014-01-25 02:36:51.

