version: 0.4.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2019
shallow_clone: true
nuget:
  disable_publish_on_pr: true
build_script:
- ps: >-
    $Script:ErrorActionPreference = [System.Management.Automation.ActionPreference]::Stop


    & .\build.ps1 -Verbose
test: off
artifacts:
- path: bin\NuGet\*.nupkg
  name: NuGet
- path: bin\AnyCPU\**\*
  name: bin
- path: binTests\**\*
  name: binTests
deploy: off
notifications:
- provider: Email
  to:
  - vitalii.maklai@gmail.com
  subject: Omnifactotum Build [AppVeyor]
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false