version: 'Build #{build} [{branch}]'
pull_requests:
  do_not_increment_build_number: false
skip_branch_with_pr: true
skip_tags: true
branches:
  only:
  - master
  - develop
  - /feature\/.*/
image: Visual Studio 2022
configuration: Release
platform: Any CPU
shallow_clone: true
nuget:
  disable_publish_on_pr: true
matrix:
  fast_finish: true
environment:
  CI_ARG_PRERELEASE_SUFFIX: '-internal'
  CI_OUT_ARG_DEPLOYMENT_VERSION: ''
  CI_OUT_ARG_DEPLOY: 'false'
for:
  -
    branches:
      only:
        - develop
    environment:
      CI_ARG_PRERELEASE_SUFFIX: '-prerelease'
    deploy: off
  -
    branches:
      only:
        - /^feature\/.*/
    deploy: off
  -
    branches:
      only:
        - master
    environment:
      CI_ARG_PRERELEASE_SUFFIX: ''
      CI_OUT_ARG_DEPLOY: 'true'
build_script:
- ps: >-
    $Script:ErrorActionPreference = [System.Management.Automation.ActionPreference]::Stop;

    Microsoft.PowerShell.Core\Set-StrictMode -Version 1;


    & .\build.ps1 `
        -Verbose `
        -BuildConfiguration $env:Configuration `
        -BuildPlatform $env:Platform `
        -EnableDotCover `
        -PrereleaseSuffix $env:CI_ARG_PRERELEASE_SUFFIX `
        -AppveyorBuild `
        -AppveyorSourceCodeRevisionId $env:APPVEYOR_REPO_COMMIT `
        -AppveyorBuildNumber $env:APPVEYOR_BUILD_NUMBER `
        -AppveyorDeploymentFlagVariableName 'CI_OUT_ARG_DEPLOY' `
        -AppveyorDeploymentVersionVariableName 'CI_OUT_ARG_DEPLOYMENT_VERSION'
test: off
artifacts:
- path: .artifacts\**\*
  name: Artifacts
deploy:
- provider: GitHub
  on:
    branch: master
    CI_OUT_ARG_DEPLOY: 'true'
  release: '$(CI_OUT_ARG_DEPLOYMENT_VERSION)'
  description: '$(APPVEYOR_PROJECT_NAME) $(CI_OUT_ARG_DEPLOYMENT_VERSION)'
  draft: true
  prerelease: true
  auth_token:
    secure: IA0JpDs4+uNdYekaXOOeVdU0sOak2Tz6zwHP1QPjdiXF+JOaqLpGkYVLW928iuEX
  artifact: Artifacts
notifications:
- provider: Email
  to:
  - '{{commitAuthorEmail}}'
  subject: '[AppVeyor] {{projectName}} {{buildVersion}}: Build {{status}} ({{branch}} @ {{commitId}})'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
