//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: global::System.Reflection.AssemblyVersion("0.1.0.8")]
[assembly: global::System.Reflection.AssemblyFileVersion("0.1.0.8")]

// Generated by the MSBuild WriteCodeFragment class on 2013-10-24 04:24:31.

