namespace Omnifactotum.SourceGenerators;

public sealed partial class GeneratedToStringSourceGenerator
{
    private static readonly string AttributeSourceCode =
        $$"""
        // <auto-generated/>

        // ReSharper disable All

        using System;

        namespace {{Constants.GeneratedToString.Attribute.Namespace}}
        {
            /// <summary>
            ///     Specifies that the annotated type will have its <see cref="object.ToString()"/> method generated according to the specified settings.
            /// </summary>
            /// <remarks>
            ///     Generated by "{{typeof(GeneratedToStringSourceGenerator).FullName}}".
            /// </remarks>
            [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
            public sealed class {{Constants.GeneratedToString.Attribute.Name}} : Attribute
            {
                public bool {{Constants.GeneratedToString.Attribute.PropertyNames.IncludeTypeName}} { get; set; }
            }
        }
        """;
}