<?xml version="1.0" encoding="utf-8"?>

<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>netstandard2.0;net461;net472;netstandard2.1;net5.0;net6.0;net7.0;net8.0;net9.0</TargetFrameworks>
        <OutputType>Library</OutputType>
    </PropertyGroup>

    <PropertyGroup>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <PropertyGroup>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <EnablePackageValidation>true</EnablePackageValidation>

        <!-- Set `GenerateCompatibilitySuppressionFile` to `true` to regenerate "CompatibilitySuppressions.xml"; then set back to `false` -->
        <GenerateCompatibilitySuppressionFile>false</GenerateCompatibilitySuppressionFile>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Omnifactotum.CompilerExtensions.Tests"/>
        <InternalsVisibleTo Include="Omnifactotum.Tests"/>
        <InternalsVisibleTo Include="Omnifactotum.Tests.Common"/>
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)'=='net461' or '$(TargetFramework)'=='net472' or '$(TargetFramework)'=='netstandard2.0' or '$(TargetFramework)'=='netstandard2.1'">
        <PackageReference Include="System.Collections.Immutable" Version="5.0.0"/>
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)'=='net461' or '$(TargetFramework)'=='net472' or '$(TargetFramework)'=='netstandard2.0'">
        <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.5.4"/>
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)'=='net461'">
        <PackageReference Include="System.ValueTuple" Version="4.5.0"/>
    </ItemGroup>

    <ItemGroup>
        <!-- Using `OutputItemType="Analyzer"` to consume own analyzer. Can be temporarily removed or set to empty string during development while needed -->
        <ProjectReference
            Include="..\Omnifactotum.CompilerExtensions\Omnifactotum.CompilerExtensions.csproj"
            OutputItemType="Analyzer"
            ReferenceOutputAssembly="false"/>
    </ItemGroup>

    <PropertyGroup>
        <EnableDefaultItems>false</EnableDefaultItems>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="**/*.cs" Exclude="**/obj/**"/>

        <Compile Include="..\Common\AssemblyInfo.Common.cs">
            <Link>Properties\AssemblyInfo.Common.cs</Link>
        </Compile>

        <None Include="**/*.md"/>

        <None Include="..\Common\Omnifactotum.snk">
            <Link>Properties\Omnifactotum.snk</Link>
        </None>

        <None Include="CompatibilitySuppressions.xml"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="$(__X_SolutionDir)\..\README.NuGet.md" Pack="true" PackagePath="/"/>

        <None
            Include="$(__X_RootSolutionOutputPath)\bin\$(Configuration)\$(MSBuildProjectName).CompilerExtensions\netstandard2.0\$(MSBuildProjectName).CompilerExtensions.dll"
            Pack="true"
            PackagePath="analyzers/dotnet/cs"
            Visible="false"/>
    </ItemGroup>

    <PropertyGroup>
        <PackageReadmeFile>README.NuGet.md</PackageReadmeFile>
    </PropertyGroup>
</Project>